### ISSUE TITLE
代理是不是没有起作用

### ISSUE THREAD

**Issue by spencercjh** [shuzijun/leetcode-editor#66]
我在公司里，平时时候Intellij IDEA都要使用System Proxy才能连上各种Server。勾选了

- [ ] proxy（HTTP Proxy）

后，出现以下Event log：
```
9/20/2019
10:00 AM	warning: request question failed,load cache

10:00 AM	error: load question failed

10:00 AM	warning: request failed
```

我的System proxy设置：

    host rb-proxy-de.bosch.com
    port 8080
    and with authentication

我能够使用这个代理正常下载各种插件，经过相关配置后也能翻过公司防火墙访问各种maven、gradle源。

我的Leetcode cn账号密码都没有问题，昨天晚上还在家里用过这个插件。

**Comment by shuzijun** [comment]
这个是依赖idea的代理配置，首先先配置一下idea的代理

**Comment by spencercjh** [comment]
好吧，我懂你意思，我都是设好的了，但还是没绕过公司防火墙，算了算了

**Comment by shuzijun** [comment]
可以提供下idea的代理配置截图么？代理功能目前只经过了本地测试，如果您愿意，可以帮助验证下

**Comment by spencercjh** [comment]
我公司防火墙不让我上传图片，我佛了。

Manual Proxy Configuration

HTTP

host name rb-proxy-de.bosch.com
port 8080


No Proxy for 127.0.0.1

proxy authentication

// ID
// PASSWORD

这个是可用的，我的插件不靠这个代理设置是下载不了的

**Comment by shuzijun** [comment]
排查配置是没问题的，麻烦通过以下两文件验证一下：
1.[test.http.zip](https://github.com/shuzijun/leetcode-editor/files/3635538/test.http.zip) 解压后粘贴到idea的工程里，运行GET方法，用来验证代理能够正确访问到leetcode网址。
![http](https://user-images.githubusercontent.com/27667179/65322075-64ad2b00-dbd8-11e9-8f55-939605de9855.png)  
2.[http-test-0.0.1-SNAPSHOT.zip](https://github.com/shuzijun/leetcode-editor/files/3635543/http-test-0.0.1-SNAPSHOT.zip) 解压后有一个jar包，用压缩软件打开这个jar，修改里面的config.properties配置项（代理相关），修改完成后，通过java -jar命令运行这个jar，输入https://www.leetcode.com，用来验证这个插件代理相关的程序能够正常访问leetcode。
![jar](https://user-images.githubusercontent.com/27667179/65322416-5c092480-dbd9-11e9-9e0e-43ea1086c1cc.png)

**Comment by spencercjh** [comment]
还是原谅我公司的firewall不让我上传图片

# test.http:

GET https://www.leetcode.com
HTTP/1.1 200 OK

能够正常访问，html都出来了


# jar:

能够正常访问，html都出来了

所以到底是哪里出问题了呢？

我刚刚又试了一下：

    9:45 AM	error: load question failed

    9:45 AM	warning: request failed

**Comment by shuzijun** [comment]
jar里面的代码和插件的代码是同一个逻辑，只是把配置抽出来了。插件还是不能访问就很奇怪了，稍后我把在插件里添加一些日志再排查一下

**Comment by JoeyHe912** [comment]
代理没有生效 +1

**Comment by ricky110** [comment]
代理不生效+1 公司也能正常下载插件，访问GET https://www.leetcode.com
HTTP/1.1 200 OK  但是链接插件的时候出现
9:43	error: 加载题目失败

9:43	warning: 请求失败

9:45	warning: 请求题目出错,将加载本地缓存

**Comment by 1106944911** [comment]
代理没有生效+1
![image](https://user-images.githubusercontent.com/5948147/73819102-c5f13600-4829-11ea-8ed9-0ca38b662f66.png)
插件能正常下载，截图代理√和没√效果一样，所以推测代理没有生效。

**Comment by hhhhappy** [comment]
我的proxy生效了，当我重启goland的之后

**Comment by shuzijun** [comment]
新的beta版本已更新,下载链接[v6.4-beta](https://github.com/shuzijun/leetcode-editor/releases/tag/v6.4-beta),这个版本的网络请求与IDE保持一致，代理与IDE保持一致，设置方法与检测参考[settings-http-proxy](https://www.jetbrains.com/help/idea/settings-http-proxy.html).

**Comment by hhhhappy** [comment]
> 新的beta版本已更新,下载链接[v6.4-beta](https://github.com/shuzijun/leetcode-editor/releases/tag/v6.4-beta),这个版本的网络请求与IDE保持一致，代理与IDE保持一致，设置方法与检测参考[settings-http-proxy](https://www.jetbrains.com/help/idea/settings-http-proxy.html).

Error occured after updating from v6.3 to v6.4-beta.

When I click login, error occured:

`java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$HttpResponseProcessor.process(HttpRequestUtils.java:150)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$HttpResponseProcessor.process(HttpRequestUtils.java:137)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.doProcess(HttpRequests.java:523)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.process(HttpRequests.java:505)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.access$100(HttpRequests.java:57)
	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:352)
	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils.executeGet(HttpRequestUtils.java:31)
	at com.shuzijun.leetcode.plugin.actions.toolbar.LoginAction.actionPerformed(LoginAction.java:30)
	at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:408)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by shuzijun** [comment]
> > 新的beta版本已更新，下载链接[v6.4-beta](https://github.com/shuzijun/leetcode-editor/releases/tag/v6.4-beta)，此版本的网络请求与IDE保持一致，代理与IDE保持一致，设置方法与检测参考[settings-http-proxy](https://www.jetbrains.com/help/idea/settings-http-proxy.html)。
> 
> 从v6.3升级到v6.4-beta后发生错误。
> 
> 当我单击登录时，发生错误：
> 
> ```
> java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
> 	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$HttpResponseProcessor.process(HttpRequestUtils.java:150)
> 	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$HttpResponseProcessor.process(HttpRequestUtils.java:137)
> 	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.doProcess(HttpRequests.java:523)
> 	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.process(HttpRequests.java:505)
> 	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.access$100(HttpRequests.java:57)
> 	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:352)
> 	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils.executeGet(HttpRequestUtils.java:31)
> 	at com.shuzijun.leetcode.plugin.actions.toolbar.LoginAction.actionPerformed(LoginAction.java:30)
> 	at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:408)
> 	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> ```
> 
> **环境：**
> 戈兰2019.2

@hhhhappy The file has been updated, please download and install again.

**Comment by hhhhappy** [comment]
> > > 新的beta版本已更新，下载链接[v6.4-beta](https://github.com/shuzijun/leetcode-editor/releases/tag/v6.4-beta)，此版本的网络请求与IDE保持一致，代理与IDE保持一致，设置方法与检测参考[settings-http-proxy](https://www.jetbrains.com/help/idea/settings-http-proxy.html)。
> > 
> > 
> > 从v6.3升级到v6.4-beta后发生错误。
> > 当我单击登录时，发生错误：
> > ```
> > java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
> > 	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$HttpResponseProcessor.process(HttpRequestUtils.java:150)
> > 	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils$HttpResponseProcessor.process(HttpRequestUtils.java:137)
> > 	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.doProcess(HttpRequests.java:523)
> > 	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.process(HttpRequests.java:505)
> > 	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests.access$100(HttpRequests.java:57)
> > 	at com.shuzijun.leetcode.plugin.utils.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:352)
> > 	at com.shuzijun.leetcode.plugin.utils.HttpRequestUtils.executeGet(HttpRequestUtils.java:31)
> > 	at com.shuzijun.leetcode.plugin.actions.toolbar.LoginAction.actionPerformed(LoginAction.java:30)
> > 	at com.shuzijun.leetcode.plugin.actions.AbstractAction$1.run(AbstractAction.java:44)
> > 	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
> > 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
> > 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
> > 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
> > 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
> > 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
> > 	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:408)
> > 	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
> > 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> > 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> > 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> > 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> > 	at java.base/java.lang.Thread.run(Thread.java:834)
> > ```
> > 
> > 
> > **环境：**
> > 戈兰2019.2
> 
> @hhhhappy The file has been updated, please download and install again.

@shuzijun It works, thanks!
