### ISSUE TITLE
NoClassDefFoundError: com/intellij/ui/jcef/JBCefApp on PyCharm 2026.2

### ISSUE THREAD

**Issue by AlanRosston** [shuzijun/leetcode-editor#770]
**Describe the bug**
After upgrading PyCharm from 2025.1.3 to 2026.2.0.1, the plugin fails to initialize on startup with `NoClassDefFoundError: com/intellij/ui/jcef/JBCefApp`. The plugin's `SupportCheck` startup activity crashes because the `JBCefApp` class cannot be resolved by the plugin classloader — even though the IDE's own JCEF version is reported as `144.0.15-262-b37` in Help → About, suggesting JCEF itself is present but not accessible/exposed to this plugin under the new build.

**To Reproduce**
1. Upgrade PyCharm to 2026.2.0.1 (build 262.8665.369)
2. Keep leetcode-editor plugin (v8.16) installed
3. Start the IDE
4. See error on startup (stack trace below)

```
java.lang.NoClassDefFoundError: com/intellij/ui/jcef/JBCefApp
	at com.shuzijun.leetcode.plugin.listener.SupportCheck.runActivity(SupportCheck.java:26)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runOldActivity(StartupManagerImpl.kt:385)
	at com.intellij.ide.startup.impl.StartupManagerImpl.doRunPostStartupActivities(StartupManagerImpl.kt:339)
	...
Caused by: java.lang.ClassNotFoundException: com.intellij.ui.jcef.JBCefApp
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
	... 19 more
```

**Software versions(*Help* -> *About*)**
- Product: PyCharm 2026.2.0.1
- Build: #PY-262.8665.369, built on July 27, 2026
- Runtime version: 25.0.3+9-b508.16 amd64
- VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
- JCEF version: 144.0.15-262-b37
- OS: Ubuntu 24.04.4 LTS (Linux 6.14.0-35-generic); glibc: 2.39; desktop: GNOME (GNOME Shell 46.0)

**Question(Optional)**
- URL: N/A (crashes on IDE startup, before opening any LeetCode page)
- Code Type: N/A
- code:
  ```
  
  ```

**Comment by shuzijun** [comment]
Due to SDK changes, the plugin is currently being updated for compatibility. In the meantime, you can manually install the Alpha version for testing:

  Install the Alpha version (https://plugins.jetbrains.com/plugin/12132-leetcode-editor/versions/alpha)

  A stable release will be published once the compatibility work is complete.

**Comment by AlanRosston** [comment]
Thanks for the fast fix! I installed the Alpha version and tested basic functionality (opening problems, submitting code) — everything works fine now, no more `NoClassDefFoundError`. 

Looking forward to the stable release. Thanks again for the great plugin!
